global using global::Terraria;
global using global::Terraria.Audio;
global using global::Terraria.DataStructures;
global using global::Terraria.Enums;
global using global::Terraria.Graphics;
global using global::Terraria.Graphics.Effects;
global using global::Terraria.GameContent;
global using global::Terraria.GameContent.Achievements;
global using global::Terraria.GameContent.Biomes;
global using global::Terraria.GameContent.Bestiary;
global using global::Terraria.GameContent.Creative;
global using global::Terraria.GameContent.Drawing;
global using global::Terraria.GameContent.Generation;
global using global::Terraria.GameContent.ItemDropRules;
global using global::Terraria.GameContent.ObjectInteractions;
global using global::Terraria.GameContent.Personalities;
global using global::Terraria.GameContent.Events;
global using global::Terraria.GameContent.Tile_Entities;
global using global::Terraria.GameContent.UI;
global using global::Terraria.Localization;
global using global::Terraria.ModLoader;
global using global::Terraria.ModLoader.IO;
global using global::Terraria.ModLoader.Config;
global using global::Terraria.ModLoader.Config.UI;
global using global::Terraria.ModLoader.Utilities;
global using global::Terraria.ObjectData;
global using global::Terraria.ID;
global using global::Terraria.IO;
global using global::Terraria.UI;
global using global::Terraria.UI.Chat;
global using global::Terraria.Utilities;
global using global::Terraria.Utilities.Terraria.Utilities;
global using global::Terraria.WorldBuilding;
global using global::Microsoft.Xna.Framework;
global using global::Microsoft.Xna.Framework.Graphics;
global using global::Newtonsoft.Json;
global using global::Newtonsoft.Json.Converters;
global using global::Newtonsoft.Json.Linq;
global using global::ReLogic.Content;
global using global::ReLogic.Utilities;
global using global::System;
global using global::System.IO;
global using global::System.IO.Pipes;
global using global::System.Linq;
global using global::System.Media;
global using global::System.Text;
global using global::System.Threading.Tasks;
global using global::System.Collections;
global using global::System.Collections.Generic;
global using global::System.ComponentModel;
global using global::System.Diagnostics;
global using global::System.Net.Mail;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.InteropServices;
global using global::BulletExpress;
global using static BulletExpress.EnergyDamage;
global using static BulletExpress.HortiDamage;
global using static BulletExpress.NewSummon;
global using static Terraria.Utils;
global using static Terraria.Tile;
global using static Terraria.ModLoader.ModContent;
global using static System.Formats.Asn1.AsnWriter;
